---

- name: disable selinux
  shell: "setenforce 0"

- selinux:
    state: disabled

- name: install apache server
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd
    - nc
    - php

- name: copy html
  copy:
    src: index.html
    dest: /var/www/html/
  notify:
    - "Restart httpd"

- name: change ssh port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Port"
    line: "Port 30122"

- name: copy nc files
  copy:
    src: "{{ item }}"
    dest: /tmp/
  with_items:
    - run_nc.sh
    - too_easy.txt
    - run_nc2.sh
    - another_es_poop.sh
    - creative_stuff
    - email.php

- name: Change email
  lineinfile:
    path: /tmp/email.php
    state: present
    regexp: '^mail'
    line: mail("{{ myemail }}","My subject",$msg);

- name: Run nc.sh
  shell: "nohup bash /tmp/run_nc.sh </dev/null >/dev/null 2>&1 &"

- name: Run nc2.sh
  shell: "nohup bash /tmp/run_nc2.sh </dev/null >/dev/null 2>&1 &"

- name: create user centos
  user:
    name: centos
    shell: /bin/bash
    state: present
    createhome: yes
  become: yes
  become_method: "sudo"

- name: Set up authorized keys for the centos user
  authorized_key: user=centos key="{{item}}"
  with_file:
    - id_rsa.pub

- name: copy motd
  copy:
    src: motd
    dest: /etc/

- name: run another_es_poop
  shell: "nohup bash /tmp/another_es_poop.sh </dev/null >/dev/null 2>&1 &"

- name: Restart ssh
  service:
    name: sshd
    state: restarted
